package com.immi.system.enums;

public enum ApplicationEventTypeEnum {
    APPLICATION_STATUS,
    APPLICATION_DOCUMENTS,
    REQUEST_FOR_EVIDENCE,
    APPLICATION_DECISION,
    NVC_CASE_NUMBER,
    NVC_CASE_INVOICE_ID,
    NVC_FEES,
    NVC_DS260,
    NVC_AFFIDAVIT,
    NVC_CIVIL_DOCUMENTS,
    NVC_CASE_DECISION,
    CONSULAR_APPOINTMENT,
    VAC_PROFILE,
    BIOMETRIC_APPOINTMENT,
    MEDICAL_APPOINTMENT,
    CONSULAR_DECISION,
    CONSULAR_STATUS,
    OATH_CEREMONY,
    APPEAL,
    PASSPORT_APPOINTMENT,
}
